version: '3.8.1'

name: djs-bot

services:
  djs-bot:
    container_name: djs-bot
    build:
      context: ..
      dockerfile: ./docker/djs-bot/Dockerfile
    restart: "unless-stopped"
    init: true
    environment:
      - TOKEN=${TOKEN}
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - DEVUID=${DEVUID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    stdin_open: true
    tty: true
    volumes:
      - ../djs-bot:/djs-bot
    ports:
      - "8080:8080"
      - "3001:3001"
    working_dir: /djs-bot
    depends_on:
      - postgres-db
    command: >
      sh -c "
      npx prisma generate && 
      npx prisma db push &&
      npm run ${ENABLE:-start}"

  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:  root
      POSTGRES_USER:      root
      POSTGRES_DB:        base
      PGPORT:             5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lavalink:
    image: fredboat/lavalink:3.7.12
    container_name: lavalink
    restart: unless-stopped
    hostname: docker.lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins
    ports:
      - 2333:2333

volumes:
  postgres_data:
